import Head from 'next/head';
import Link from 'next/link';
import { Container, Heading, List, Box } from '@chakra-ui/react';

export default function Client() {
  const patientName = 'Arjun Gupta';
  const exercises = ['Lying Back Twist', 'Yawning Dog Stretch', 'Hamstring Extension'];
  const loggedIn = true;

  return (
    <div>
      <Head>
        <title>client</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container py={16} maxW="3xl">
        <Heading pb={4}>{patientName}</Heading>

        <List>
          {exercises.map(e => (
            <Box bg="blue.500" w="100%" color="white" p={4} my={4} borderRadius={10} key={e}>
              <Link href="/exercise">{e}</Link>
            </Box>
          ))}
        </List>
      </Container>
    </div>
  );
}
