import Head from 'next/head';
import {
  Flex,
  Stack,
  Heading,
  Text,
  FormControl,
  FormLabel,
  Input,
  Box,
  Center,
  Checkbox,
  Button,
  useColorModeValue,
  Link,
  HStack
} from '@chakra-ui/react';
import { useRouter } from 'next/router';
// import { ColorModeSwitcher } from '../components/ColorModeSwitcher';

export default function Login() {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        minH={'100vh'}
        align={'center'}
        justify={'center'}
        backgroundColor="red.200"
        bg={useColorModeValue('gray.50', 'gray.800')}
      >
        <Stack spacing={8} mx={'auto'} maxW={'lg'} py={12} px={6}>
          <Stack align={'center'}>
            <Heading fontSize={'4xl'}>Physical Therapy</Heading>
            <Text fontSize={'lg'} color={'gray.600'}>
              Sign in to your account
            </Text>
          </Stack>
          <Box
            backgroundImage="url('/downloads/antivirus.jpeg')"
            backgroundPosition="center"
            backgroundRepeat="no-repeat"
          />
          <Box rounded={'lg'} bg={useColorModeValue('white', 'gray.700')} boxShadow={'lg'} p={8}>
            <Stack spacing={4}>
              <FormControl id="email">
                <FormLabel>Email address</FormLabel>
                <Input type="email" />
              </FormControl>
              <FormControl id="password">
                <FormLabel>Password</FormLabel>
                <Input type="password" />
              </FormControl>
              <Stack spacing={10}>
                <Stack
                  direction={{ base: 'column', sm: 'row' }}
                  align={'start'}
                  justify={'space-between'}
                >
                  <Checkbox>Remember me</Checkbox>
                  <Link color={'blue.400'}>Forgot password?</Link>
                </Stack>
                <Center>
                  <HStack>
                    {/* <Center> */}
                    <Text>New to us?</Text>
                    <Link color="blue.400" href="#">
                      Sign Up
                    </Link>
                  </HStack>
                  {/* </Center> */}
                </Center>
                {/* <Link href="/"> */}
                <Button
                  bg={'blue.400'}
                  color={'white'}
                  _hover={{
                    bg: 'blue.500'
                  }}
                  onClick={() => router.push('/')}
                >
                  {/* <Link href=""></Link> */}
                  Sign in
                </Button>
                {/* </Link> */}
              </Stack>
            </Stack>
          </Box>
        </Stack>
      </Flex>
    </div>
  );
}
