import Head from 'next/head';
import { Container, Heading, List, SimpleGrid, Box, Center } from '@chakra-ui/react';
import Link from 'next/link';

export default function Home() {
  const patientName = 'Dr. Koot';
  const clients = ['Qendrim Veseli', 'Sarah Belal', 'Arvind Kasiliya'];

  return (
    <div>
      <Head>
        <title>physical therapist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container py={16} maxW="3xl">
        <Heading pb={4}>{patientName}</Heading>

        <SimpleGrid minChildWidth="120px" spacing="40px">
          {clients.map(e => (
            <Center
              bg="blue.500"
              height="80px"
              color="white"
              p={4}
              my={4}
              borderRadius={10}
              key={e}
            >
              <Link href="/client">{e}</Link>
            </Center>
          ))}
          {/* <Box bg="tomato" height="80px"></Box>
          <Box bg="tomato" height="80px"></Box>
          <Box bg="tomato" height="80px"></Box>
          <Box bg="tomato" height="80px"></Box>
          <Box bg="tomato" height="80px"></Box>
          <Box bg="tomato" height="80px"></Box> */}
        </SimpleGrid>
      </Container>
    </div>
  );
}
